module.exports = {
  alum: "Alum",
  anthracite: "Anthracite",
  bismuthinite: "Bismuthinite",
  bituminouscoal: "Bituminous Coal",
  borax: "Borax",
  cassiterite: "Cassiterite",
  cinnabar: "Cinnabar",
  diamond: "Diamond",
  emerald: "Emerald",
  fluorite: "Fluorite",
  galena: "Galena",
  gold: "Gold",
  graphite: "Graphite",
  halite: "Halite",
  hematite: "Hematite",
  ilmenite: "Ilmenite",
  kernite: "Kernite",
  lapis: "Lapis Lazuli",
  lignite: "Lignite",
  limonite: "Limonite",
  malachite: "Malachite",
  magnetite: "Magnetite",
  nativecopper: "Native Copper",
  pentlandite: "Pentlandite",
  peridot: "Peridot",
  phosphorite: "Phosphorite",
  quartz: "Quartz",
  silver: "Silver",
  sphalerite: "Sphalerite",
  sulfur: "Sulfur",
  sylvite: "Sylvite"
}